dist: trusty
language:
  - c
sudo: required

env:
  global:
    - CI_SOURCE_PATH=${PWD}
    - CURRENT_DIR=${CI_SOURCE_PATH}
    - OPENCMIDE_DIR=${CURRENT_DIR}/ROBOTIS_OpenCM-v1.0.2
    - LOCAL_INO_SRCS = ${CURRENT_DIR}/sketchbook/igmr_dynamixel_control/igmr_dynamixel_control.ino
    - TARGET=${CURRENT_DIR}/sketchbook/igmr_dynamixel_control/igmr_dynamixel_control

install:
  - sudo apt-get install arduino arduino-mk avrdude-doc task-c-devel gcc-doc gcc-4.2 libjna-java-doc libyaml-shell-perl groff
script:
  - make clean
  - make
